version: '3'


services:
<<<<<<< HEAD
=======
 
 
>>>>>>> f5c2a7c8e35f6523f711f1fd36cd6c370bd93a7f
  redis:
    image: redis

  textbelt:
    build: 
        context: ./textbelt
        dockerfile: Dockerfile
        args:
             email: your_email@something.com
    depends_on:
      - redis

  nginx: 
    build: ./nginx
    ports:
            - 80:80
    depends_on:
      - textbelt
